server:
  # 配置端口
  port: 8101
  # 配置统一前缀
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: mypoise_backend
  servlet:
    multipart:
      max-file-size: 5MB
  # 允许使用application-local.yml 配置文件
  profiles:
    active: local
  # 1. mysql 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_library
    username: root
    password: 20020901lcb
  #  2. 邮箱配置
  mail:
    # QQ邮箱的SMTP服务器地址
    host: smtp.qq.com
    username: 2500822924@qq.com
    emailFrom: 2500822924@qq.com
    # 邮箱授权码
    password: wafwvxozmyoqdjbg
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # 3. Redis 配置
  redis:
    database: 3
    host: localhost
    port: 6379
    timeout: 5000
    #password: 123456
  session:
    store-type: redis
    timeout: 2592000
  # 4. 动态分库分表配置（空间图片分表）
  shardingsphere:
    datasource:
      names: cloud_library
      cloud_library:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud_library
        username: root
        password: 20020901lcb
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: cloud_library.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: integrated.graphic_and_text.collaboration.mypoise.manage.sharding.PictureShardingAlgorithm
    props:
      sql-show: true

# 对象存储
cos:
  client:
    accessKey:
    secretKey:
    region:
    bucket:
mybatis-plus:
  # mybatis-plus 配置
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #仅在开发环境需要记录日志
  global-config:
    enable-sql-runner: true
    db-config:
      # 配置逻辑删除，包括逻辑删除字段、逻辑已删除值、逻辑未删除值
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true # 开启knife4j
  openapi:
    title: "图文一体化协同平台"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - integrated.graphic_and_text.collaboration.mypoise.controller






















